<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.8.1 setup script
 * Date: Sun, 27 May 2018 21:34:25 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: Database [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'Database';
$cfg['Servers'][$i]['host'] = 'database';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = '4yH#hO(B:3qD82GwON5\'/1MROGG>J]O';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
